env:
  global: {secure: AF6nHse8HI2j3ZdwKzHu23QmhhxTYz9/fJKRJbM5m2p2YD/HXIejryzgE7gd1sBsbzD1QCMk6041kpLBDqvX+UC0HMfVaXmg2daMAQhDuWHmyXHG0S9iCbuvJ5QX1vsTNP/1ZEr0sFQ4Ue+ZEiXjkEaV1jsoPlmPVttzSagHsF8=}
install: pip install -e git+https://github.com/getnikola/nikola.git#egg=nikola
language: python
python: ['2.7']
script: ./build_and_deploy.sh
