before_install: sudo apt-get install -qq python-lxml
branches:
  only: [master]
env:
  global: {secure: fMaELtEJoz9fPhSoQsvNqxkpLppRajgYIQ9mm8ZGM6nNHyDC04F+w+8Ac2Uw6vhc6EvDFYNWTcSVNAkWv7UKvklsL2HskB4V1NN+aKIzpOHlt9zmmPrFvz4SPpC2z2QfzihIoig2Aeg+HwiVDh5CaO16j3vgkJUIm9foBVvU154=}
install: pip install nikola webassets
language: python
python: ['2.7']
script: bash travis_build_n_deploy.sh
virtualenv: {system_site_packages: true}
